package org.kok202.dluid.domain.action;

public enum ActionType {
    REFRESH_COMPONENT_LIST,
    BLOCK_CONNECTION_START,
    BLOCK_CONNECTION_MOVE,
    BLOCK_CONNECTION_RELEASE,
    TEST_SUCCEED,
    TEST_ENABLE,
    TEST_DISABLE,
    TEST_RESULT_CLEAR,
    TEST_TARGET_RESULT_REFRESH,
}
