package org.kok202.dluid.domain.action;

public enum ActionType {
    MODEL_ENABLE,
    REFRESH_MODEL_INFORMATION,
    REFRESH_COMPONENT_LIST,
    REFRESH_TRAINING_FILE_LOADER,
    REFRESH_TRAINING_LOG,
    REFRESH_TRAINING_BUTTON_ENABLE,
    REFRESH_TRAINING_BUTTON_DISABLE,
    REFRESH_TEST_LOG,
    REFRESH_TEST_INPUT_LATYER_INFORMATION,
    BLOCK_CONNECTION_START,
    BLOCK_CONNECTION_MOVE,
    BLOCK_CONNECTION_RELEASE,
    TEST_SUCCEED,
    TEST_ENABLE,
    TEST_DISABLE,
    TEST_RESULT_CLEAR,
    TEST_TARGET_RESULT_REFRESH,
}
